# These are supported funding model platforms

github: elisaul77
patreon: elisaul77
ko_fi: elisaul77
buy_me_a_coffee: elisaul77
paypal: eflorezp
custom: ["https://paypal.me/eflorezp", "https://buymeacoffee.com/elisaul77", "https://ko-fi.com/elisaul77", "https://patreon.com/elisaul77"]
