version: '3.8'
services:
  kybercore:
    build: .
    container_name: kybercore
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - ./kybercore.log:/app/kybercore.log
    environment:
      - PYTHONUNBUFFERED=1
    command: ["/bin/sh", "-c", "uvicorn src.api.main:app --host 0.0.0.0 --port 8000 2>&1 | tee /app/kybercore.log"]
    restart: unless-stopped
# Agrega aquí otros servicios (db, cache, etc.) si es necesario
