version: '3.8'

services:
  slicer-api:
    build: .
    ports:
      - "8001:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./output:/app/output
      - ./config:/app/config
    environment:
      - PYTHONUNBUFFERED=1
      - DISPLAY=:99
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3